version: "3.8"

services:
  db-produto:
    image: postgres:16.2
    container_name: "containerBancoDeDados"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./scriptBancoDeDados:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    restart: always
  app-produto:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: app-sistema-produto
    environment:
      POSTGRES_HOST: db-produto:5432
      RABBITMQ_HOST: 172.17.0.1
    ports:
      - "8080:8080"
    depends_on:
      - db-produto
    restart: always