version: "3.8"

services:
  db:
    image: postgres:16.2
    hostname: db
    container_name: "containerBancoDeDados"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./../scriptBancoDeDados:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'containerRabbitMQ'
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - db
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  app:
    build:
      context: ./../
      dockerfile: Dockerfile
    container_name: app-sistema-produto
    environment:
      POSTGRES_HOST: db:5432
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    restart: always
